### ISSUE TITLE
Can't collect a configuration when the username is 'root' on Junos Routers.

### ISSUE THREAD

**Issue by kazubu** [taijiji/GitRouter#4]
When I try the tool with a inventory file which has some Junos routers with 'root' user, the collected configuration is not valid as below.

```
$ cat inventory.json
[
    {
        "hostname" : "host1",
        "username" : "user",
        "password" : "pass123",
        "ipv4"     : "192.168.1.2",
        "os"       : "JUNOS"
    },
    {
        "hostname" : "host2",
        "username" : "root",
        "password" : "rootpass123",
        "ipv4"     : "192.168.1.3",
        "os"       : "JUNOS"
    }
]

$ cat host1.txt
show configuration | no-more
## Last commit: 2015-08-31 07:46:05 JST by root
version 12.3R9-S1;
...(snip)...

$ cat host2.txt
show configuration | no-more
show: Command not found.
no-more: Command not found.
```

I recommend you to use the following command when the username is 'root' because the login shell of 'root' user is not Junos CLI but csh.

`ssh root@ipaddr "cli show configuration \| no-more"`

Thanks,
Kazuki Shimizu

**Comment by taijiji** [comment]
Supported JUNOS root mode. https://github.com/taijiji/ConfigCollector/commit/4a743c17633470a9c74667b963dbd30ea0b509d9

Thank you for Issue and truly sorry for delay.
